name: Update Contributors List

on:
  pull_request:
    types:
      - closed

jobs:
  update-contributors:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Get PR author information
      id: author-info
      run: |
        echo "::set-output name=username::$(echo ${{ github.event.pull_request.user.login }})"
        echo "::set-output name=useravatar::$(curl -s https://api.github.com/users/${{ github.event.pull_request.user.login }} | jq -r '.avatar_url')"
    
    - name: Update contributors.md
      run: |
        echo "Adding contributor ${{ steps.author-info.outputs.username }}..."
        echo "\n### [${{ steps.author-info.outputs.username }}](${{ steps.author-info.outputs.useravatar }})\n" >> CONTRIBUTORS.md
        echo "![](${{ steps.author-info.outputs.useravatar }})" >> CONTRIBUTORS.md

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add CONTRIBUTORS.md
        git commit -m "Add contributor ${{ steps.author-info.outputs.username }}"
        git push
